<!--
SPDX-FileCopyrightText: 2020-2026 Friedrich von Never <friedrich@fornever.me>

SPDX-License-Identifier: MIT
-->

<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Description>
            This package is part of Fabricator, an infrastructure automation framework. Fabricator.Core provides the core interfaces for various deployment functionality.
        </Description>
    </PropertyGroup>

    <ItemGroup>
        <Compile Include="Resource.fs" />
        <Compile Include="AssemblyInfo.fs" />
    </ItemGroup>

</Project>
