<!--
SPDX-FileCopyrightText: 2020-2026 Friedrich von Never <friedrich@fornever.me>

SPDX-License-Identifier: MIT
-->

<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Description>
            This package is part of Fabricator, an infrastructure automation framework. Fabricator.Console provides the command-line interface for Fabricator, including argument parsing, logging facilities, and orchestration of resource deployment execution. It processes the resources and manages the apply/check workflow lifecycle.
        </Description>
    </PropertyGroup>

    <ItemGroup>
        <Compile Include="TaskExecutor.fs" />
        <Compile Include="Lowering.fs" />
        <Compile Include="Report.fs" />
        <Compile Include="OrderedLog.fs" />
        <Compile Include="ExecutionUi.fs" />
        <Compile Include="Commands.fs" />
        <Compile Include="EntryPoint.fs" />
        <Compile Include="AssemblyInfo.fs" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Fabricator.Core\Fabricator.Core.fsproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Spectre.Console" Version="0.57.2" />
    </ItemGroup>

</Project>
