# SPDX-FileCopyrightText: 2020-2025 Friedrich von Never <friedrich@fornever.me>
#
# SPDX-License-Identifier: MIT

name: Main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  main:
    runs-on: ${{ matrix.environment }}
    strategy:
      matrix:
        environment:
          - macos-13
          - ubuntu-22.04
          - windows-2022
    env:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      NUGET_PACKAGES: ${{ github.workspace }}/.github/nuget-packages
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: '5.0.302'
      - name: NuGet Cache
        uses: actions/cache@v3
        with:
          path: ${{ env.NUGET_PACKAGES }}
          key: ${{ runner.os }}.nuget.${{ hashFiles('**/*.fsproj') }}
      - name: Build
        run: dotnet build
      - name: Run unit tests
        run: dotnet test
        working-directory: Fabricator.Tests
      - name: Run integration tests
        run: dotnet test
        working-directory: Fabricator.IntegrationTests
  encoding:
    runs-on: ubuntu-24.04
    steps:
      - name: Check out the sources
        uses: actions/checkout@v5
      - name: Verify encoding
        shell: pwsh
        run: Install-Module VerifyEncoding -Repository PSGallery -RequiredVersion 2.2.1 -Force && Test-Encoding
